"""Lazy in-process loaders for trained model artifacts.

Loaded objects are cached for the lifetime of the worker process, so
subsequent predictions skip disk I/O. The cache is intentionally simple
— for the workload we expect (a handful of models, hundreds of MB at
most), per-process caching beats any external store.
"""
from __future__ import annotations

import threading
from pathlib import Path
from typing import Any

import joblib
from fastapi import HTTPException

from app.core.config import settings
from app.inference.registry import MODEL_REGISTRY, ModelMeta


# ─── Cache state ──────────────────────────────────────────────────────

_lock = threading.Lock()
_model_cache: dict[str, Any] = {}
_scaler_cache: Any | None = None
_transformer_scaler_cache: Any | None = None


# ─── Public API ───────────────────────────────────────────────────────

def get_model_meta(model_id: str) -> ModelMeta:
    """Look up registry metadata or raise 404."""
    meta = MODEL_REGISTRY.get(model_id)
    if meta is None:
        raise HTTPException(
            status_code=404,
            detail=f"Unknown model_id '{model_id}'. "
                   f"Valid options: {sorted(MODEL_REGISTRY)}.",
        )
    return meta


def is_artifact_available(meta: ModelMeta) -> bool:
    """Return True iff the artifact file exists on disk."""
    return _artifact_path(meta).is_file()


def load_scaler() -> Any:
    """Load the StandardScaler fit on the training split (FR-09).

    The scaler is shared across all models — never re-fit on uploaded
    data. Cached for the worker lifetime.
    """
    global _scaler_cache
    if _scaler_cache is not None:
        return _scaler_cache

    with _lock:
        if _scaler_cache is not None:
            return _scaler_cache
        path = settings.artifact_dir / "scaler.pkl"
        if not path.is_file():
            raise HTTPException(
                status_code=503,
                detail=f"Scaler artifact not found at {path}. "
                       f"Place 'scaler.pkl' under app/backend/artifacts/ "
                       f"(distributed separately, see README).",
            )
        _scaler_cache = joblib.load(path)
        return _scaler_cache


def load_transformer_scaler() -> Any:
    """Load Xu Li's per-feature StandardScaler for the TransformerFusionLite (T7).

    The transformer was trained on a *different* normalisation regime than
    the classical models: per-feature (8 mean/std pairs over all timesteps)
    rather than per-(timestep × feature) (160 pairs). Feeding it the
    classical `scaler.pkl` outputs silently corrupts predictions, so the
    transformer code path uses this dedicated scaler instead.

    Generated by `src/deep_learning/extract_transformer_scaler.py` from
    the same training split Xu used.
    """
    global _transformer_scaler_cache
    if _transformer_scaler_cache is not None:
        return _transformer_scaler_cache

    with _lock:
        if _transformer_scaler_cache is not None:
            return _transformer_scaler_cache
        path = settings.artifact_dir / "transformer_scaler.pkl"
        if not path.is_file():
            raise HTTPException(
                status_code=503,
                detail=f"Transformer scaler not found at {path}. "
                       f"Run scripts/extract_transformer_scaler.py to "
                       f"generate it from the training .npz.",
            )
        _transformer_scaler_cache = joblib.load(path)
        return _transformer_scaler_cache


def load_model(model_id: str) -> Any:
    """Load and cache a trained model by id.

    Raises
    ------
    HTTPException(404)
        If `model_id` is not in the registry.
    HTTPException(503)
        If the artifact file does not exist on disk (e.g. transformer
        weights have not yet been delivered — see T7).
    """
    meta = get_model_meta(model_id)

    if model_id in _model_cache:
        return _model_cache[model_id]

    with _lock:
        if model_id in _model_cache:
            return _model_cache[model_id]
        path = _artifact_path(meta)
        if not path.is_file():
            raise HTTPException(
                status_code=503,
                detail=(
                    f"Model '{model_id}' artifact not yet available "
                    f"(expected at {path}). "
                    f"This is normal for the TransformerFusionLite model "
                    f"until T7 is completed."
                ),
            )

        if meta.is_dl:
            model = _load_torch_model(path)
        else:
            model = joblib.load(path)
        _model_cache[model_id] = model
        return model


# ─── Internals ────────────────────────────────────────────────────────

def _artifact_path(meta: ModelMeta) -> Path:
    return settings.artifact_dir / meta.artifact


def _load_torch_model(path: Path) -> Any:
    """Load a PyTorch checkpoint deterministically (NFR-05).

    Imported lazily so the backend does not require torch unless a deep
    learning model is actually requested. We also import the model class
    so that `torch.load` can resolve `TransformerFusionLiteModel` when
    the artifact was saved as a full pickled module (vs a bare state_dict).
    Use `scripts/convert_xu_transformer.py` to convert Xu Li's `.pth`
    (state_dict only) into a loadable full-model `.pt`.
    """
    import torch  # type: ignore

    # Eager import so unpickling can resolve the class by name.
    from app.inference.transformer_model import TransformerFusionLiteModel  # noqa: F401

    torch.manual_seed(42)
    model = torch.load(path, map_location="cpu", weights_only=False)
    if hasattr(model, "eval"):
        model.eval()
    return model
